/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-primary-fixed-variant": "#224d53",
        "on-secondary-fixed-variant": "#584400",
        "secondary-container": "#fed977",
        "surface-container-low": "#f2f4f6",
        "inverse-primary": "#a3ced5",
        "on-tertiary-container": "#afadac",
        "tertiary": "#2b2b2b",
        "secondary": "#755b00",
        "inverse-surface": "#2e3132",
        "surface": "#f8f9fb",
        "on-secondary-fixed": "#241a00",
        "on-background": "#191c1e",
        "tertiary-container": "#414141",
        "background": "#f8f9fb",
        "on-primary-container": "#8ab4bb",
        "outline-variant": "#c0c8c9",
        "tertiary-fixed": "#e5e2e1",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#e6c364",
        "secondary-fixed": "#ffe08f",
        "surface-dim": "#d9dadc",
        "surface-bright": "#f8f9fb",
        "on-surface-variant": "#404849",
        "error": "#ba1a1a",
        "primary": "#003036",
        "surface-container-highest": "#e1e2e4",
        "on-tertiary-fixed-variant": "#474746",
        "inverse-on-surface": "#f0f1f3",
        "primary-container": "#1b474d",
        "primary-fixed-dim": "#a3ced5",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "primary-fixed": "#beeaf1",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1e",
        "surface-container-high": "#e7e8ea",
        "error-container": "#ffdad6",
        "surface-tint": "#3b656b",
        "on-error": "#ffffff",
        "outline": "#71787a",
        "on-tertiary-fixed": "#1c1b1b",
        "on-secondary-container": "#785d00",
        "surface-container": "#edeef0",
        "on-primary-fixed": "#001f23",
        "surface-variant": "#e1e2e4"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
